name: gotong-royong-dev

services:
  gotong-api:
    profiles: ["api"]
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      APP_ENV: "${APP_ENV:-development}"
      PORT: 3100
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      DATA_BACKEND: surrealdb
      SURREAL_ENDPOINT: ws://surrealdb:8000
      SURREAL_NS: "${SURREAL_NS:-gotong}"
      SURREAL_DB: "${SURREAL_DB:-chat}"
      SURREAL_USER: "${SURREAL_USER:-root}"
      SURREAL_PASS: "${SURREAL_PASS:-root}"
      REDIS_URL: redis://redis:6379
      JWT_SECRET: "${JWT_SECRET:-dev-secret}"
      AUTH_DEV_BYPASS_ENABLED: "${AUTH_DEV_BYPASS_ENABLED:-true}"
      TRIAGE_OPERATOR_STUB_ENABLED: "${TRIAGE_OPERATOR_STUB_ENABLED:-false}"
      CHAT_REALTIME_TRANSPORT: "${CHAT_REALTIME_TRANSPORT:-local}"
      CHAT_REALTIME_CHANNEL_PREFIX: "${CHAT_REALTIME_CHANNEL_PREFIX:-gotong:chat:realtime}"
      CHAT_ATTACHMENT_STORAGE_BACKEND: "${CHAT_ATTACHMENT_STORAGE_BACKEND:-local}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://minio:9000}"
      S3_BUCKET: "${S3_BUCKET:-gotong-royong-evidence-dev}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY:-minioadmin}"
      S3_SECRET_KEY: "${S3_SECRET_KEY:-minioadmin}"
      S3_REGION: "${S3_REGION:-us-east-1}"
      WEBHOOK_ENABLED: "${WEBHOOK_ENABLED:-false}"
    ports:
      - "${API_PORT:-3100}:3100"
    depends_on:
      surrealdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3100/health"]
      interval: 5s
      timeout: 3s
      retries: 20

  gotong-worker:
    profiles: ["worker"]
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      APP_ENV: "${APP_ENV:-development}"
      LOG_LEVEL: "${LOG_LEVEL:-info}"
      DATA_BACKEND: surrealdb
      SURREAL_ENDPOINT: ws://surrealdb:8000
      SURREAL_NS: "${SURREAL_NS:-gotong}"
      SURREAL_DB: "${SURREAL_DB:-chat}"
      SURREAL_USER: "${SURREAL_USER:-root}"
      SURREAL_PASS: "${SURREAL_PASS:-root}"
      REDIS_URL: redis://redis:6379
      JWT_SECRET: "${JWT_SECRET:-dev-secret}"
      CHAT_REALTIME_TRANSPORT: "${CHAT_REALTIME_TRANSPORT:-local}"
      CHAT_REALTIME_CHANNEL_PREFIX: "${CHAT_REALTIME_CHANNEL_PREFIX:-gotong:chat:realtime}"
      WEBHOOK_ENABLED: "${WEBHOOK_ENABLED:-false}"
      WORKER_QUEUE_PREFIX: "${WORKER_QUEUE_PREFIX:-gotong:jobs}"
    depends_on:
      surrealdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Optional local monitoring stack.
  # Enable with: `docker compose -f compose.dev.yaml --profile monitoring up -d`
  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:v2.55.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./deploy/monitoring/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  surrealdb:
    image: surrealdb/surrealdb:v3.0.0
    command:
      [
        "start",
        "memory",
        "--log",
        "info",
        "--user",
        "${SURREAL_USER:-root}",
        "--pass",
        "${SURREAL_PASS:-root}",
        "--bind",
        "0.0.0.0:8000",
      ]
    ports:
      - "${SURREAL_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "/surreal", "is-ready", "--endpoint", "ws://127.0.0.1:8000"]
      interval: 2s
      timeout: 2s
      retries: 30

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30

  # Optional local object storage for evidence uploads.
  # Enable with: `docker compose -f compose.dev.yaml --profile storage up -d`
  minio:
    profiles: ["storage"]
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin}"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9000/minio/health/ready"]
      interval: 2s
      timeout: 2s
      retries: 30
