pub mod adaptive_path;
pub mod auth;
pub mod chat;
pub mod contributions;
pub mod discovery;
pub mod error;
pub mod evidence;
pub mod idempotency;
pub mod identity;
pub mod jobs;
pub mod mode;
pub mod moderation;
pub mod ontology;
pub mod ports;
pub mod ranking;
pub mod siaga;
pub mod util;
pub mod vault;
pub mod vouches;
pub mod webhook;

pub type DomainResult<T> = Result<T, error::DomainError>;
