/**
 * Track Color Utility — maps track hint labels to Tailwind CSS class strings.
 *
 * Track hints are now dynamically generated by AI, so any string is valid.
 * Well-known tracks (tuntaskan, wujudkan, telusuri, rayakan, musyawarah)
 * have DNA tokens defined in app.css. Unknown tracks fall back to a
 * neutral color set.
 */

import type { TrackHint } from '$lib/types';

export interface TrackColorSet {
	/** Background class (e.g., 'bg-tuntaskan') */
	bg: string;
	/** Light background class (e.g., 'bg-tuntaskan/10') */
	bgLight: string;
	/** Text class (e.g., 'text-tuntaskan') */
	text: string;
	/** Border class (e.g., 'border-tuntaskan') */
	border: string;
}

/** Neutral fallback for AI-generated tracks without a dedicated color token. */
const FALLBACK_COLORS: TrackColorSet = {
	bg: 'bg-kayu',
	bgLight: 'bg-kayu/10',
	text: 'text-kayu',
	border: 'border-kayu'
};

/** Well-known track colors with dedicated DNA tokens. */
const KNOWN_TRACK_COLORS: Record<string, TrackColorSet> = {
	tuntaskan: {
		bg: 'bg-tuntaskan',
		bgLight: 'bg-tuntaskan/10',
		text: 'text-tuntaskan',
		border: 'border-tuntaskan'
	},
	wujudkan: {
		bg: 'bg-wujudkan',
		bgLight: 'bg-wujudkan/10',
		text: 'text-wujudkan',
		border: 'border-wujudkan'
	},
	telusuri: {
		bg: 'bg-telusuri',
		bgLight: 'bg-telusuri/10',
		text: 'text-telusuri',
		border: 'border-telusuri'
	},
	rayakan: {
		bg: 'bg-rayakan',
		bgLight: 'bg-rayakan/10',
		text: 'text-rayakan',
		border: 'border-rayakan'
	},
	musyawarah: {
		bg: 'bg-musyawarah',
		bgLight: 'bg-musyawarah/10',
		text: 'text-musyawarah',
		border: 'border-musyawarah'
	}
};

/** Get the full color class set for a track. Falls back to neutral for unknown tracks. */
export function trackColors(track: TrackHint): TrackColorSet {
	return KNOWN_TRACK_COLORS[track] ?? FALLBACK_COLORS;
}

/** Get just the background class for a track. Falls back to neutral for unknown tracks. */
export function trackBgClass(track: TrackHint): string {
	return (KNOWN_TRACK_COLORS[track] ?? FALLBACK_COLORS).bg;
}
